/opt and /mnt/data can rw

diff --git a/buildroot-2021.05/board/milkv/duo/overlay/etc/init.d/S10auto_mount b/buildroot-2021.05/board/milkv/duo/overlay/etc/init.d/S10auto_mount
--- a/buildroot-2021.05/board/milkv/duo/overlay/etc/init.d/S10auto_mount
+++ b/buildroot-2021.05/board/milkv/duo/overlay/etc/init.d/S10auto_mount
@@ -5,21 +5,38 @@ ${CVI_SHOPTS}
 case "$1" in
 start)
 ENV_DLFLAG=`fw_printenv dl_flag 2>/dev/null |awk -F= '{print $2}'`
+printf "Mounting SYSTEM partition\n"
+ubiattach /dev/ubi_ctrl -m 5
+if [ $? != 0  ]; then
+ubiformat -y /dev/mtd5
+ubiattach /dev/ubi_ctrl -m 5
+ubimkvol /dev/ubi1 -N SYSTEM -m
+fi
+if [ ! -c /dev/ubi1_0 ]; then
+mdev -s
+fi
+mount -t ubifs -o sync /dev/ubi1_0 /opt
+if [ $? != 0  ]; then
+echo 'Mount SYSTEM failed, Try formatting and remounting'
+ubimkvol /dev/ubi1 -N SYSTEM -m
+mount -t ubifs -o sync /dev/ubi1_0 /opt
+fi
+ENV_DLFLAG=`fw_printenv dl_flag 2>/dev/null |awk -F= '{print $2}'`
 printf "Mounting CFG partition\n"
 ubiattach /dev/ubi_ctrl -m 6
 if [ $? != 0  ]; then
 ubiformat -y /dev/mtd6
 ubiattach /dev/ubi_ctrl -m 6
-ubimkvol /dev/ubi1 -N CFG -m
+ubimkvol /dev/ubi2 -N CFG -m
 fi
-if [ ! -c /dev/ubi1_0 ]; then
+if [ ! -c /dev/ubi2_0 ]; then
 mdev -s
 fi
-mount -t ubifs -o sync /dev/ubi1_0 /mnt/cfg
+mount -t ubifs -o sync /dev/ubi2_0 /mnt/cfg
 if [ $? != 0  ]; then
 echo 'Mount CFG failed, Try formatting and remounting'
-ubimkvol /dev/ubi1 -N CFG -m
-mount -t ubifs -o sync /dev/ubi1_0 /mnt/cfg
+ubimkvol /dev/ubi2 -N CFG -m
+mount -t ubifs -o sync /dev/ubi2_0 /mnt/cfg
 fi
 ENV_DLFLAG=`fw_printenv dl_flag 2>/dev/null |awk -F= '{print $2}'`
 printf "Mounting DATA partition\n"
@@ -27,16 +44,16 @@ ubiattach /dev/ubi_ctrl -m 7
 if [ $? != 0  ]; then
 ubiformat -y /dev/mtd7
 ubiattach /dev/ubi_ctrl -m 7
-ubimkvol /dev/ubi2 -N DATA -m
+ubimkvol /dev/ubi3 -N DATA -m
 fi
-if [ ! -c /dev/ubi2_0 ]; then
+if [ ! -c /dev/ubi3_0 ]; then
 mdev -s
 fi
-mount -t ubifs -o sync /dev/ubi2_0 /mnt/data
+mount -t ubifs -o sync /dev/ubi3_0 /mnt/data
 if [ $? != 0  ]; then
 echo 'Mount DATA failed, Try formatting and remounting'
-ubimkvol /dev/ubi2 -N DATA -m
-mount -t ubifs -o sync /dev/ubi2_0 /mnt/data
+ubimkvol /dev/ubi3 -N DATA -m
+mount -t ubifs -o sync /dev/ubi3_0 /mnt/data
 fi
 ;;
 esac
